Repository catenax-ng/catenax-at-home, pull requests merged in 2022-05, with the labels that each got.

#40 Fix response parsing of creating negotiation & transfer-process regarding the newest EDC version
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/ApiWrapperController.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/model/NegotiationId.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/model/TransferId.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/service/ContractNegotiationService.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/service/HttpProxyService.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/service/TransferProcessService.java
Labels: bug

#47 Fix wrong type interpretation for references in submodel descriptor
  api-wrapper/services/semantics/framework/src/main/java/net/catenax/semantics/framework/aas/model/OneOfReference.java
Labels: bug

#45 Add OpenAPI documentation for API-Wrapper
  api-wrapper/services/api-wrapper/build.gradle.kts
  api-wrapper/services/api-wrapper/openapi.md
  api-wrapper/services/api-wrapper/openapi/openApi.yaml
  api-wrapper/services/api-wrapper/openapi/openApiInfo.yaml
Labels: enhancement

#51 Add helm charts
  api-wrapper/services/api-wrapper/build.gradle.kts
  deployment/helm/aas-proxy/.helmignore
  deployment/helm/aas-proxy/Chart.yaml
  deployment/helm/aas-proxy/README.md
  deployment/helm/aas-proxy/templates/NOTES.txt
  deployment/helm/aas-proxy/templates/_helpers.tpl
  deployment/helm/aas-proxy/templates/deployment.yaml
  deployment/helm/aas-proxy/templates/hpa.yaml
  deployment/helm/aas-proxy/templates/imagepullsecret.yaml
  deployment/helm/aas-proxy/templates/ingress.yaml
  deployment/helm/aas-proxy/templates/service.yaml
  deployment/helm/aas-proxy/templates/serviceaccount.yaml
  deployment/helm/aas-proxy/values.yaml
  deployment/helm/api-wrapper/.helmignore
  deployment/helm/api-wrapper/Chart.yaml
  deployment/helm/api-wrapper/README.md
  deployment/helm/api-wrapper/templates/NOTES.txt
  deployment/helm/api-wrapper/templates/_helpers.tpl
  deployment/helm/api-wrapper/templates/configmap.yaml
  deployment/helm/api-wrapper/templates/deployment.yaml
  deployment/helm/api-wrapper/templates/hpa.yaml
  deployment/helm/api-wrapper/templates/imagepullsecret.yaml
  deployment/helm/api-wrapper/templates/ingress.yaml
  deployment/helm/api-wrapper/templates/service.yaml
  deployment/helm/api-wrapper/templates/serviceaccount.yaml
  deployment/helm/api-wrapper/values.yaml
  kubernetes/consumer-api-wrapper.config/configuration.properties
  kubernetes/consumer-control-plane.config/cert.pfx
  kubernetes/consumer-control-plane.config/configuration.properties
  kubernetes/consumer-control-plane.config/vault.properties
  kubernetes/consumer-data-plane.config/configuration.properties
  kubernetes/infrastructure/central-services.yml
  kubernetes/infrastructure/consumer-aas.yaml
  kubernetes/infrastructure/consumer-edc.yaml
  kubernetes/infrastructure/provider-aas.yaml
  kubernetes/infrastructure/provider-edc.yaml
  kubernetes/provider-backend-service.config/configuration.properties
  kubernetes/provider-control-plane.config/cert.pfx
  kubernetes/provider-control-plane.config/configuration.properties
  kubernetes/provider-control-plane.config/vault.properties
  kubernetes/provider-data-plane.config/configuration.properties
Labels: documentation, enhancement

#59 Rename api-wrapper & proxy container images
  api-wrapper/config/consumer-api-wrapper.config/configuration.properties
  api-wrapper/config/consumer-control-plane.config/configuration.properties
  api-wrapper/docker-compose.yml
  api-wrapper/hack/tagAndPublishContainerImages.sh
  getting-started-guide/config/consumer-api-wrapper.config/configuration.properties
  getting-started-guide/config/consumer-control-plane.config/configuration.properties
  getting-started-guide/docker-compose.yml
Labels: bug, enhancement

#65 Replace edc image builds with pre-build images & allow debugging with older edc versions
  api-wrapper/config/consumer-data-plane.config/configuration.properties
  api-wrapper/config/provider-data-plane.config/configuration.properties
  api-wrapper/docker-compose.yml
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/service/ContractNegotiationService.java
  api-wrapper/services/api-wrapper/src/main/java/org/eclipse/dataspaceconnector/apiwrapper/connector/sdk/service/TransferProcessService.java
  getting-started-guide/config/consumer-data-plane.config/configuration.properties
  getting-started-guide/config/provider-data-plane.config/configuration.properties
Labels: enhancement
